export type BlockType =
  | 'DOCUMENT_TITLE'
  | 'DOCUMENT_HEADING'
  | 'HEADING'
  | 'SUBHEADING'
  | 'PARAGRAPH'
  | 'QUESTION_CANDIDATE'
  | 'OPTION_CANDIDATE'
  | 'ANSWER_CANDIDATE'
  | 'EXPLANATION_CANDIDATE'
  | 'TABLE'
  | 'LIST'
  | 'HEADER'
  | 'FOOTER'
  | 'NOISE'
  | 'UNKNOWN';

export type QuestionType =
  | 'MCQ'
  | 'SINGLE_CHOICE_MCQ'
  | 'MULTI_SELECT'
  | 'MULTIPLE_CHOICE'
  | 'TRUE_FALSE'
  | 'MATCHING'
  | 'STATEMENT_BASED'
  | 'ASSERTION_REASON'
  | 'FILL_IN_THE_BLANK'
  | 'NUMERICAL'
  | 'TABLE_BASED'
  | 'PASSAGE'
  | 'IMAGE_BASED'
  | 'MAP_BASED'
  | 'ORDERING'
  | 'MULTI_PART'
  | 'DESCRIPTIVE'
  | 'UNKNOWN';

export type ImportStatus =
  | 'PENDING'
  | 'UPLOADING'
  | 'ANALYZING'
  | 'EXTRACTING'
  | 'OCR_PROCESSING'
  | 'PARSING'
  | 'ALIGNING'
  | 'VALIDATING'
  | 'REVIEW_READY'
  | 'IMPORTING'
  | 'COMPLETED'
  | 'FAILED';

export type ValidationStatus =
  | 'PASS'
  | 'WARNING'
  | 'REVIEW_REQUIRED'
  | 'ERROR';

export type AnswerSourceLocation =
  | 'IMMEDIATE'
  | 'END_OF_SECTION'
  | 'END_OF_DOCUMENT'
  | 'ANSWER_KEY_PAGE'
  | 'EMBEDDED_EXPLANATION';
